-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 23:13:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_move_rent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_move_rent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_move_rent` ;
USE `db_move_rent` ;

-- -----------------------------------------------------
-- Table `db_move_rent`.`tbl_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_move_rent`.`tbl_pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_move_rent`.`tbl_ciclomotor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_move_rent`.`tbl_ciclomotor` (
  `cm_id` INT NOT NULL AUTO_INCREMENT,
  `cm_nome` VARCHAR(50) NOT NULL,
  `cm_ano` INT NOT NULL DEFAULT 2000,
  `cm_cor` VARCHAR(15) NULL,
  PRIMARY KEY (`cm_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_move_rent`.`tbl_locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_move_rent`.`tbl_locacao` (
  `lc_id` INT NOT NULL AUTO_INCREMENT,
  `lc_data_locacao` DATE NOT NULL DEFAULT CURRENT_DATE,
  `lc_hora_locacao` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIME',
  `lc_local_locacao` VARCHAR(50) NOT NULL,
  `lc_id_pessoa` INT NOT NULL,
  `lc_id_ciclomotor` INT NOT NULL,
  PRIMARY KEY (`lc_id`),
  INDEX `fk_tbl_locacao_id_ciclomotor_idx` (`lc_id_ciclomotor` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_locacao_id_pessoa`
    FOREIGN KEY ('lc_id_pessoa')
    REFERENCES `db_move_rent`.`tbl_pessoa` ('idPessoa')
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_locacao_id_ciclomotor`
    FOREIGN KEY (`lc_id_ciclomotor`)
    REFERENCES `db_move_rent`.`tbl_ciclomotor` (`cm_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_move_rent`.`tbl_trajetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_move_rent`.`tbl_trajetos` (
  `id_trajeto` INT NOT NULL AUTO_INCREMENT,
  `tj_data_trajeto` DATE NOT NULL DEFAULT CURRENT_DATE,
  `tj_hora_trajeto` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIME',
  `tj_local_trajeto` VARCHAR(55) NULL,
  `tj_id_locacao` INT NOT NULL,
  PRIMARY KEY (`id_trajeto`),
  INDEX `fk_tbl_trajetos_id_locacao_idx` (`tj_id_locacao` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_trajetos_id_locacao`
    FOREIGN KEY (`tj_id_locacao`)
    REFERENCES `db_move_rent`.`tbl_locacao` (`lc_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
