-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 21:40:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,
NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_db` ;
USE `biblioteca_db` ;

-- -----------------------------------------------------
-- Table `biblioteca_db`.`tb_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`tb_aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `ra_aluno` INT NOT NULL,
  `nome_aluno` VARCHAR(50) NOT NULL,
  `email_aluno` VARCHAR(100) NOT NULL,
  `telefone_aluno` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `ra_aluno_UNIQUE` (`ra_aluno` ASC) VISIBLE,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`tb_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`tb_livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `isbn_livro` INT NOT NULL,
  `nome_livro` VARCHAR(100) NOT NULL,
  `autor_livro` VARCHAR(45) NOT NULL,
  `num_paginas_livro` INT NOT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `isbn_livro_UNIQUE` (`isbn_livro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`tb_colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`tb_colaborador` (
  `id_colaborador` INT NOT NULL AUTO_INCREMENT,
  `cpf_colaborador` VARCHAR(14) NOT NULL,
  `nome_colaborador` VARCHAR(50) NOT NULL,
  `email_colaborador` VARCHAR(50) NOT NULL,
  `cargo_colaborador` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `cpf_colaborador_UNIQUE` (`cpf_colaborador` ASC) VISIBLE,
  PRIMARY KEY (`id_colaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`tb_emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_db`.`tb_emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_retirada_emprestimo` DATE NOT NULL DEFAULT CURRENT_DATE,
  `data_devolucao_emprestimo` DATE NOT NULL,
  `id_livro_emprestimo` INT NOT NULL,
  `id_aluno_emprestimo` INT NOT NULL,
  `id_colaborador_emprestimo` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_tb_emprestimo_livro_isbn_idx` (`id_livro_emprestimo` ASC) VISIBLE,
  INDEX `fk_tb_emprestimo_aluno_idx` (`id_aluno_emprestimo` ASC) VISIBLE,
  INDEX `fk_tb_emprestimo_colaborador_idx` (`id_colaborador_emprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_emprestimo_livro`
    FOREIGN KEY (`id_livro_emprestimo`)
    REFERENCES `biblioteca_db`.`tb_livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_emprestimo_aluno`
    FOREIGN KEY (`id_aluno_emprestimo`)
    REFERENCES `biblioteca_db`.`tb_aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_emprestimo_colaborador`
    FOREIGN KEY (`id_colaborador_emprestimo`)
    REFERENCES `biblioteca_db`.`tb_colaborador` (`id_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
